"""
pages/reports.py — CareerOS Mission Report Page
Displays the live automated report generated by engine.reporting.
"""

import streamlit as st
import sys
import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from engine.reporting.reports import generate_system_report
from storage import db

st.title("📊 Mission Report")
st.caption("Auto-generated daily summary of your CareerOS activity and market signals.")
st.divider()

# Period selector
col_period, col_btn = st.columns([3, 1])
with col_period:
    period = st.radio("Report Period", ["Daily", "Weekly"], horizontal=True, key="report_period")
with col_btn:
    regenerate = st.button("🔄 Refresh Report", use_container_width=True)

# Generate / load from session
cache_key = f"report_{period}"
if regenerate or cache_key not in st.session_state:
    with st.spinner(f"Generating {period} report..."):
        report_md = generate_system_report(period=period)
        st.session_state[cache_key] = report_md
        st.toast(f"✅ {period} report generated!", icon="📊")

report_md = st.session_state.get(cache_key, "")

if report_md:
    # Download button
    st.download_button(
        label="💾 Download Report (.md)",
        data=report_md,
        file_name=f"careeros_{period.lower()}_report.md",
        mime="text/markdown",
        use_container_width=False,
    )
    st.divider()
    st.markdown(report_md)
