import type { Metadata } from "next";

export const metadata: Metadata = { title: "Mission Report | CareerOS" };

async function getReport(): Promise<string | null> {
  try {
    const res = await fetch("http://localhost:8000/report/latest", { cache: "no-store" });
    if (!res.ok) return null;
    const data = await res.json() as { content?: string };
    return data.content ?? null;
  } catch {
    return null;
  }
}

function MetricPill({ label, value, accent }: { label: string; value: string; accent: string }) {
  return (
    <div className="glass p-4 text-center">
      <div className="text-xs uppercase tracking-widest text-gray-500 mb-1">{label}</div>
      <div className={`text-2xl font-bold ${accent}`}>{value}</div>
    </div>
  );
}

export default async function ReportPage() {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold gradient-text">Mission Report</h1>
          <p className="text-gray-400 text-sm mt-1">Auto-generated daily intelligence briefing.</p>
        </div>
        <span className="text-xs text-gray-500 bg-gray-800 px-3 py-1.5 rounded-full">
          {new Date().toLocaleDateString("id-ID", { weekday: "long", day: "numeric", month: "long" })}
        </span>
      </div>

      {/* Pipeline Funnel */}
      <div className="grid grid-cols-4 gap-3">
        <MetricPill label="Scouted"   value="—" accent="text-indigo-400" />
        <MetricPill label="Applied"   value="—" accent="text-blue-400" />
        <MetricPill label="Interview" value="—" accent="text-yellow-400" />
        <MetricPill label="Offer"     value="—" accent="text-green-400" />
      </div>

      {/* Report Body */}
      <div className="glass p-6">
        <div className="flex items-center gap-3 mb-5">
          <span className="text-2xl">📋</span>
          <div>
            <div className="font-semibold text-white">Daily Intelligence Report</div>
            <div className="text-xs text-gray-400">Generated by CareerOS v4.0 reporting engine</div>
          </div>
        </div>
        <div className="space-y-4 text-sm text-gray-300 leading-relaxed">
          <div className="bg-gray-900/60 rounded-lg p-4">
            <div className="text-xs uppercase tracking-widest text-gray-500 mb-3">🤖 RL Agent Health</div>
            <p className="text-gray-400">Run <code className="text-indigo-400 bg-indigo-500/10 px-1 rounded">python careeros_cli.py report</code> to generate a fresh report and save it to <code className="text-indigo-400 bg-indigo-500/10 px-1 rounded">reports/</code>.</p>
          </div>
          <div className="bg-gray-900/60 rounded-lg p-4">
            <div className="text-xs uppercase tracking-widest text-gray-500 mb-3">🌐 Market Pulse</div>
            <p className="text-gray-400">The reporting engine reads live skill frequency data from the database and market signals from the pulse module. Connect to the backend to see real-time data.</p>
          </div>
          <div className="bg-gray-900/60 rounded-lg p-4">
            <div className="text-xs uppercase tracking-widest text-gray-500 mb-3">🗺️ Cluster Heat Map</div>
            <p className="text-gray-400">Apply to more jobs to populate cluster performance data. The heat map will appear here once you have application outcomes recorded.</p>
          </div>
        </div>
      </div>

      {/* CLI shortcut */}
      <div className="glass border-l-4 border-indigo-500 p-4">
        <div className="text-xs uppercase tracking-widest text-gray-500 mb-2">💡 Quick Actions</div>
        <div className="font-mono text-sm text-indigo-300 space-y-1">
          <div>$ python careeros_cli.py report</div>
          <div>$ python careeros_cli.py report --weekly</div>
          <div>$ python careeros_cli.py benchmark</div>
        </div>
      </div>
    </div>
  );
}
